version: "3.3"
services:
  api:
    container_name: xapotest-api
    build: ./api
    ports: ['8080:8080']
    volumes: ['.:/api']
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_SERVER=database
    links:
      - database

  database:
    container_name: xapotest-database
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - xapotest-db:/var/lib/mysql

volumes:
  xapotest-db:
